[book]
authors = ["Ivan Alexeev"]
language = "en"
multilingual = false
src = "src"
title = "C++ course notes"

[output.html]
default-theme = "ayu"
git-repository-url = "https://github.com/ivnalxv/main_page"
